### ISSUE TITLE
Error pages doesn't load correct CSS

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#199]
Check views and CSS for views like 404 not found!

**Comment by marsimunic** [comment]
In laravel 5.4, I fix the problem change in public/css/all.css in the following way 
in all the reference url instead of put url (/fonts) place url (../fonts)

**Comment by riquerolim** [comment]
I have the same problem

![image](https://cloud.githubusercontent.com/assets/25722819/23705839/063f18f6-03e2-11e7-8800-28bcb23fb8a2.png)

Help me please

**Comment by acacha** [comment]
Sorry are you having these problems with a fresh installation of adminlte-laravel. I've installed a new fresh installation today and no problems at all for example see: https://demo.adminlte.acacha.org/asdasdsdaasdasdasd

**Comment by riquerolim** [comment]
Your link is broken :(

What is the correct version of laravel to use?

**Comment by marsimunic** [comment]
Perform an installation of adminlte-laravel today on Windows 7 and I didn´t have problems.
But today also install admintlte - laravel in Linux Debian, and I had the problem with the references to the sources URL from the file public/css/all.css
That's why I had to put "..." before the path:
@font-face {}
font-family: "Ionicons";
src: url (..) /fonts/ionicons.eot?bdf1d30681cf87986c385eea78e8de9a);
....
}
Is it possible that I have problems with apache in debia linux?

**Comment by riquerolim** [comment]
I am using Windows 10, Wampp Server with MySQL and Laravel 5.4.

Could you tell me where exactly I make the correction by putting the (..)?

**Comment by clebersa** [comment]
Hello guys,

I opened a similar issue (https://github.com/acacha/adminlte-laravel/issues/209) some time ago.

I found the problem and a solution, which can be seen at https://github.com/acacha/adminlte-laravel/issues/209#issuecomment-285206463, and I am waiting for @acacha to take a look at that to see what we can do about it.

Have a good day.

**Comment by clebersa** [comment]
Hello @riquerolim and @marsimunic,

I believe I solved this issue in last pull request merged to this project. The merge was done this morning. Please, check that and let us know if that solved your problem so @acacha can close this issue as well.

Have a good day!

**Comment by clebersa** [comment]
Hello everybody,

I want to share something with you because I think it might be helpful. This applies when you are serving your application with an alias with Apache.

Although I fixed the issue as I mentioned, the files I changed are from the folder `vendor/acacha/admin-lte-template-laravel` and when you run `npm run dev`, some files will be replaced by the new compiled ones.  Thus, the files from adminlte-template-laravel, gotten through `php artisan vendor:publish --tag=adminlte --force` for example, will be replaced and the URL for the resources will be wrong again.

To solve that, I made some changes to the `webpack.mix.js` file. Instead of using sass to generate the `app.css`, I used less to generate secondary CSS resources and then compile them into `all.css`, and I also added an option to the less function. So, instead of having this:
```js
mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/app-landing.js', 'public/js/app-landing.js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .less('node_modules/bootstrap-less/bootstrap/bootstrap.less', 'public/css/bootstrap.css')
   .less('resources/assets/less/adminlte-app.less','public/css/adminlte-app.css')
   .less('node_modules/toastr/toastr.less','public/css/toastr.css')
   .combine([
       'public/css/app.css',
       'node_modules/admin-lte/dist/css/skins/_all-skins.css',
       'public/css/adminlte-app.css',
       'node_modules/icheck/skins/square/blue.css',
       'public/css/toastr.css'
   ], 'public/css/all.css')

...
```
I have this now:
```js
mix.js('resources/assets/js/app.js', 'public/js')
   .js('resources/assets/js/app-landing.js', 'public/js/app-landing.js')
   .extract(['jquery-slimscroll'])
   .less('node_modules/bootstrap-less/bootstrap/bootstrap.less', 'public/css/bootstrap.css', {rootpath:"/myappalias/fonts/"})
   .less('node_modules/font-awesome/less/font-awesome.less', 'public/css/font-awesome.css', {rootpath:"/myappalias/fonts/"})
   .less('resources/assets/less/adminlte-app.less','public/css/adminlte-app.css')
   .less('node_modules/toastr/toastr.less','public/css/toastr.css')
   .combine([
       'url(https://fonts.googleapis.com/css?family=Raleway:300,400,600)',
       'public/css/bootstrap.css',
       'public/css/font-awesome.css',
       'node_modules/admin-lte/dist/css/skins/_all-skins.css',
       'public/css/adminlte-app.css',
       'node_modules/icheck/skins/square/blue.css',
       'public/css/toastr.css'
   ], 'public/css/all.css')

...
```
When you compare, you can see I replaced the `sass()` function by 2 `less()` functions for bootstrap and font-awesome. For the `less()` function, I added an option called `rootpath` that [will added a suffix to the resources generated in the CSS files](http://lesscss.org/usage/). As I do not need ionicons in my project, I did not add that. Also, in the `combine()` function, I removed the `app.css` and I added one CSS that is gotten through an URL, and the `bootstrap.css` and `font-awesome.css` generated with less. I based these action in the `resources/assets/sass/app.scss`.

I hope this helps someone, once it was very helpful for me to get my project working.

Bye.
