### ISSUE TITLE
error with modal dialog

### ISSUE THREAD

**Issue by maswahjoe** [acacha/adminlte-laravel#210]
Hi,
I have problem with modal dialog, the modal can't acces. 

## Detailed description
if i click button the display of modal like this :

![image](https://cloud.githubusercontent.com/assets/16728223/23510917/5ad8c3f8-ff96-11e6-9973-2c3ff9e8c39c.png)

if I change the CSS file to app or admin-lte  the modal can be accessed but the layout so messy.

## Your environment
is there someone who can help me.
I look forward for your feedback.
Thank's for  your time

**Comment by maswahjoe** [comment]
problem solving. thank's

**Comment by acacha** [comment]
@maswahjoe Have you solved the problem? Please can you tell us how?

**Comment by maswahjoe** [comment]
yes i did, I just change all.css with AdminLTE.css and app.css

**Comment by clebersa** [comment]
Hi @maswahjoe,

I had the same issue and I found the solution somewhere on the internet. You do not need to change your CSS to fix that. Instead, add `data-backdrop="false"` to your modal tag and it will work fine. The HTML will look like this:
```html
<div class="modal fade " id="my-id" aria-labelledby="My Modal" role="dialog" data-backdrop="false">
...
</div>
```

This issue was mentioned before at https://github.com/acacha/adminlte-laravel/issues/179 and fixed. Recent versions of AdminLTE Laravel has it fixed. However, it is not properly styled yet: the elements inside the modal have the flat style, including the modal itself. Should I report this problem in a new issue or can I report it on https://github.com/acacha/adminlte-laravel/issues/179 and then you will reopen it, @acacha?

Bye.

**Comment by maswahjoe** [comment]
thank's @clebersa , I'll try later

**Comment by acacha** [comment]
One more think i'm not sure it works but I think it could help. It seems maybe is a problem of versions in less and sass versions of bootstrap (in some previous installations you could have diferent versions)

See file: https://github.com/acacha/adminlte-laravel/blob/master/package.json

Try to fix version to:

"bootstrap-less": "3.3.7",
"bootstrap-sass": "3.3.7",
