### ISSUE TITLE
adminlte-laravel install not working

### ISSUE THREAD

**Issue by nolafs** [acacha/adminlte-laravel#225]
Hi,

When I try to run adminlte-laravel install, I get an error:

/Volumes/HD 2/Users/olaf/.composer/vendor/bin/llum package  AdminLTE
sh: /Volumes/HD: No such file or directory

Any idea why?

Cheers
Olaf

**Comment by clebersa** [comment]
Hi @nolafs,

I believe the problem is related to your folder (partition maybe) name: `HD 2`. The space in its name is probably the cause of the problem. Can you rename that folder and try again? If that is an option, maybe we should try to find a way to rewrite that path using a `\`: `/Volumes/HD\ 2/Users/olaf/.composer/vendor/bin/llum`.

Just as an advice, I would avoid using spaces in the folder names. That can be problematic sometimes.

Good luck.

**Comment by clebersa** [comment]
Hi @nolafs and @acacha,

I investigated the problem and I think this will be something to do with https://github.com/acacha/adminlte-laravel-installer. Some work will be necessary in the https://github.com/acacha/adminlte-laravel-installer/blob/master/src/Console/InstallCommand.php to enable it to use correctly a path with spaces.

I can try to make a pull request later. Should I go for it, @acacha?

Bye.

**Comment by nolafs** [comment]
Hi,

It would super helpful because I cannot rename my volumes. Would screw up a lot.  I kinda suspected this is the issue. 

Cheers
Olaf

**Comment by acacha** [comment]
@clebersa a PR will be nice thansk for your time!

**Comment by clebersa** [comment]
Hi guys,

These are the pull requests to solve the problem:
- https://github.com/acacha/adminlte-laravel-installer/pull/13
- https://github.com/acacha/llum/pull/32

I tested as described in the pull request and it worked fine.

Bye.

**Comment by acacha** [comment]
Thanks @clebersa Good job! I accepted the PR an tagged new versions for adminlte laralve installer an acacha llum. @nolafs please update your packages and please let us know if it worked for you!
