### ISSUE TITLE
How to republish assets folder after pull latest updade from git

### ISSUE THREAD

**Issue by kaalees** [acacha/adminlte-laravel#270]
## Detailed description
I already installed laravel adminlte and pull the update from repository but i want publish assets folder only is this poosible

Provide a detailed description of the change or addition you are proposing.

Make it clear if the issue is a bug, an enhancement or just a question.

## Context

Why is this change important to you? How would you use it?

How can it benefit other users?

## Possible implementation

Not obligatory, but suggest an idea for implementing addition or change.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* Version used (e.g. PHP 5.6, HHVM 3):
* Operating system and version (e.g. Ubuntu 16.04, Windows 7):
* Link to your project:
* ...
* ...

OS : Mac
Laravel 5.4

**Comment by acacha** [comment]
As every Laravel project you can use publish command:

```php
$ php artisan vendor:publish
```

But be carefull about this command because publish all files for all you Laravel package dependencies so filter using provider or tags:

```php
$ php artisan vendor:publish --provider="Vendor\Providers\PackageServiceProvider" --tag="config"
```

So use:

```php
$ php artisan vendor:publish --provider="Acacha\AdminLTETemplateLaravel\Providers\AdminLTETemplateServiceProvider" --tag="config"
```
The list of all files that are published to your app could be seen at file:

https://github.com/acacha/adminlte-laravel/blob/master/src/AdminLTE.php

also see the package serivce provider.

See also Laravel docs:
- https://laravel.com/docs/5.0/packages
