### ISSUE TITLE
fontawesome-webfonts not found

### ISSUE THREAD

**Issue by pmirandaarias** [acacha/adminlte-laravel#272]
On windows, all works ok (img, css, etc) but console shows that 

http://localhost:8080/fonts/fontawesome-webfont.woff2?af7ae505a9eed503f8b8e6982036873e
are not found (when I open register)

**Comment by acacha** [comment]
Check original files in public folder:

https://github.com/acacha/adminlte-laravel/tree/master/public/fonts

Do you miss any file in your public folder?

**Comment by pmirandaarias** [comment]
Now I installed it in Centos and I'm getting the same problem. Look:

![image](https://cloud.githubusercontent.com/assets/20463330/26605236/456612ae-455b-11e7-8071-0c7bd92d7d3d.png)

it's only with fonts, it doens't use a relative path. For example, the img are correct:

![image](https://cloud.githubusercontent.com/assets/20463330/26605289/6f340b7c-455b-11e7-9333-93641ed4477f.png)

it's accessing to `myip/projectname/public/` in my case  `192.168.1.131/pnp/public`

**Comment by pmirandaarias** [comment]
In `all.css` there is:

`src: url(/fonts/glyphi...`
I just replaced with:
`src: url(../fonts/glyphi...`
and it works.

**Comment by acacha** [comment]
Ok as in previous issues is related to using Alias (midomain.com/app) instead of full domain (myapp.com). I think is not possible to cover all options in a single solution (feel free to create a PR with tests in different environments) but I think you will have to adapt always you files if using Aliases.

See also https://github.com/acacha/adminlte-laravel/issues/209
