### ISSUE TITLE
show theme after install

### ISSUE THREAD

**Issue by tux-world** [acacha/adminlte-laravel#30]
after install on laravel how to show demo of this theme?

**Comment by acacha** [comment]
Ummm all demo is not installed only Login/Register/Remember password page and basic home page.

Maybe in future I will add this but my idea is like something optional, maybe a branch in git:

 $ git checkout demo

See what you need in the demo then come back to your app with

 $ git checkout master

Because normally you are not interested in mixing your app and demo.

**Comment by acacha** [comment]
Closed duplicate issue https://github.com/acacha/adminlte-laravel/issues/56
