### ISSUE TITLE
Error in Classes before install with previous app name

### ISSUE THREAD

**Issue by roldandvg** [acacha/adminlte-laravel#373]
Hi, excellent work with this package

I would like to tell you that at the time of installing this package in a project in which there was already an application name as namespace, when trying to execute any command it generates a class error not found. This is because a namespace was already predetermined as the name of the application and when installing adminlte-template it is installed under the default namespace of laravel App.

I consider that it should be taken into account for future versions the one that is installed under the namespace that have been defined in the psr-4 of the composer.json, that way it would avoid problems in large applications.

## My enviroment

for development I have the following environment:

* PHP 7.1
* Ubuntu 16.04

**Comment by acacha** [comment]
Thanks for you recommendation. The project intention is to work only with new Laravel Fresh installation. Other cases may need manual programmer intervention. I try to focus because If I try to adapt this simple project it could be easily convert in a unmaintanable project.

You or whoever can also propose pull request or make a fork of this project to adapt to other needs.
