### ISSUE TITLE
Update to Bootstrap 4

### ISSUE THREAD

**Issue by Denis4yk** [acacha/adminlte-laravel#397]
Are there any plans to update to Bootstrap 4?

**Comment by nieka** [comment]
Currently there is no stable release of AdminLTE with bootsrap 4. See [AdminLTE 3.0 Plans](https://github.com/almasaeed2010/AdminLTE/issues/710).  

But since it is in the dev channel since a week it wouldn't seem a bad idea to start working on integration of the new version of Admin LTE. 

But i don't know what the plans of @acacha  are on upgrading to admin LTE v3?

**Comment by acacha** [comment]
As @nieka says it's too soon to upgrade to Bootstrap 4.0 . As soon as I can and Adminlte 3.0 is released I will try to make the upgrade.

**Comment by Denis4yk** [comment]
@acacha 

Thank you for the answer and extensive support of your package. ☃️🌟

**Comment by renanalvesbr** [comment]
Also waiting for the update for Bootstrap 4...
