### ISSUE TITLE
 Auth not working/Session not persisting

### ISSUE THREAD

**Issue by s2010** [acacha/adminlte-laravel#80]
I'm trying to add a middleware to my routes and I can't figure out what's wrong. 
```
Route::auth();
Route::group(['middleware'=>['web', 'auth']], function () {
    Route::get('/', function () {
        return view('auth/login');
    });
    Route::get('/home', 'HomeController@index');
    Route::get('/home/calendar', function () {
        return view('admin.calendar');
    });
});
Route::group(['middleware'=>'admin'], function () {
    Route::resource('admin/users', 'AdminUsersController');
});
```

I've been unable to get my sessions to persist to the admin/dashboard route. I've established that the following is true: - My form validates and submits - Authentication takes place - User is redirected
But then the Auth::check() on redirect fails and sends me back to the login page. I've come to the conclusion that the App\Http\Middleware\Authenticate::handle() function is getting a null guard value.
What am I missing here???
I'm complete newbie with Laravel, so forgive my inexperience .

**Comment by Maeldor** [comment]
Try including the `web` middleware with your admin routes. I believe the web middleware is what provides session support (and CRSF protection, etc.), so you'll need it wherever you require authentication.

Almost every route is likely to need the web middleware, with exceptions being things like APIs. In fact, since v5.2.27 the web middleware is [applied by default](https://github.com/laravel/laravel/commit/5c30c98db96459b4cc878d085490e4677b0b67ed) to all routes to avoid this issue.

**Comment by acacha** [comment]
Hi @s2010 as @Maeldor said web group middleware is needed I hope you've solved you issue if not feel free to ask again!
